import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";
import { tokens } from "../tokens/schema";
import { contrastRatio, formatOklch, parseOklch } from "./oklch";
import { THEME_PRESETS } from "./presets";
import { exportPreset, importTheme, readImportedPresets } from "./theme-import";
import {
  NEUTRAL_CHROMA_MAX,
  SURFACE_TINT_BOUNDS,
  contrastFg,
  type ResolvedMode,
  type ThemePreset,
} from "./tokens";

// Nord from tinted-theming/schemes (MIT). GitHub Dark Default is the `colors`
// block generated by primer/github-vscode-theme 6.3.5 (MIT).
const fixture = (name: string) =>
  readFileSync(new URL(`./__fixtures__/${name}`, import.meta.url), "utf8");
const NORD = fixture("nord.yaml");
const GITHUB_DARK = fixture("github-dark-default.json");

function imported(text: string) {
  const result = importTheme(text);
  if (!result.ok) throw new Error(`import failed: ${result.error}`);
  return result.preset;
}

/** The accent reads as text on the page and behind its own text, in both modes. */
function expectAccentPassesAA(preset: ThemePreset) {
  for (const mode of ["light", "dark"] as ResolvedMode[]) {
    const mo = preset.overrides[mode] ?? {};
    const primary = mo.palette?.primary;
    if (!primary) continue;
    const ground = formatOklch(
      tokens.neutral.bg[mode].l,
      mo.neutralChroma ?? 0,
      mo.neutralHue ?? 0,
    );
    expect(contrastRatio(primary, ground), `${preset.name} ${mode} on page`).toBeGreaterThanOrEqual(
      4.5,
    );
    expect(
      contrastRatio(primary, contrastFg(primary)),
      `${preset.name} ${mode} text`,
    ).toBeGreaterThanOrEqual(4.5);
  }
}

function expectWithinBounds(preset: ThemePreset) {
  for (const mode of ["light", "dark"] as ResolvedMode[]) {
    const mo = preset.overrides[mode] ?? {};
    expect(mo.neutralChroma ?? 0).toBeLessThanOrEqual(NEUTRAL_CHROMA_MAX);
    if (mo.surfaceBase) {
      const { l, c } = parseOklch(mo.surfaceBase);
      const b = SURFACE_TINT_BOUNDS[mode];
      expect(l).toBeGreaterThanOrEqual(b.minL);
      expect(l).toBeLessThanOrEqual(b.maxL);
      expect(c).toBeLessThanOrEqual(b.maxC);
    }
  }
}

describe("importTheme: base16", () => {
  it("maps Nord onto both modes, keeping its hues and darkening the light-mode accent", () => {
    const nord = imported(NORD);

    expect(nord).toMatchObject({
      id: expect.stringMatching(/^imported:nord-/),
      name: "Nord",
      imported: true,
    });
    // Nord's accent is too light to read on a white page, so only contrast is adjusted.
    expect(nord.adjustments).toEqual(["contrast"]);

    const dark = nord.overrides.dark!;
    const light = nord.overrides.light!;
    // base00 keeps its hue and lightness in dark mode; light mode uses our lightness.
    expect(parseOklch(dark.surfaceBase!).h).toBeCloseTo(264.2, 0);
    expect(parseOklch(dark.surfaceBase!).l).toBeCloseTo(0.324, 2);
    expect(parseOklch(light.surfaceBase!).l).toBe(parseOklch(tokens.surface.base.light).l);
    // Greys contribute hue and chroma only.
    expect(dark.neutralHue).toBeCloseTo(264, -1);
    expect(dark.neutralChroma).toBeGreaterThan(0);
    // base0D is the accent: unchanged in dark mode, darker in light mode.
    expect(parseOklch(dark.palette!.primary!).l).toBeCloseTo(0.697, 2);
    expect(parseOklch(light.palette!.primary!).l).toBeLessThan(0.6);
    expect(parseOklch(light.palette!.primary!).h).toBeCloseTo(248.7, 0);
    // Status colours near our hues are taken at our lightness.
    expect(parseOklch(dark.palette!.danger!).l).toBe(
      parseOklch(tokens.palette.danger.dark.value).l,
    );

    expectAccentPassesAA(nord);
    expectWithinBounds(nord);
  });

  it("accepts the legacy layout with a scheme name and bare hex values", () => {
    const legacy = NORD.replace('name: "Nord"', 'scheme: "Nord Legacy"')
      .replace(/^system:.*\n|^variant:.*\n|^palette:\n/gm, "")
      .replace(/^ {2}/gm, "")
      .replace(/"#/g, '"');
    const preset = imported(legacy);
    expect(preset.name).toBe("Nord Legacy");
    expect(preset.overrides.dark).toEqual(imported(NORD).overrides.dark);
  });
});

describe("importTheme: VS Code", () => {
  it("maps GitHub Dark Default, softening the near-black sidebar and lifting the accent", () => {
    // Pasted files are JSONC; a leading comment and a trailing comma must not break parsing.
    const pasted = `// GitHub Dark Default\n${GITHUB_DARK.replace(/\n}\s*$/, ",\n}\n")}`;
    const github = imported(pasted);

    expect(github.name).toBe("GitHub Dark Default");
    // sideBar.background (#010409) is darker than a surface may go; focusBorder needs lifting.
    expect(github.adjustments).toEqual(["contrast", "softened"]);
    const dark = github.overrides.dark!;
    expect(parseOklch(dark.surfaceBase!).l).toBe(SURFACE_TINT_BOUNDS.dark.minL);
    // focusBorder (#1f6feb) is the accent, not the green button.background.
    expect(parseOklch(dark.palette!.primary!).h).toBeCloseTo(259.7, 0);
    expect(parseOklch(dark.palette!.primary!).l).toBeGreaterThan(0.569);

    expectAccentPassesAA(github);
    expectWithinBounds(github);
  });
});

describe("importTheme: JSONC", () => {
  it("strips trailing commas only outside strings", () => {
    const text = `{
      // a comment with "quotes", ]
      "name": "Odd, ] name, }",
      "colors": { "editor.background": "#1e1e1e", /* inline */ "focusBorder": "#3794ff", },
    }`;
    expect(imported(text).name).toBe("Odd, ] name, }");
  });
});

describe("importTheme: invalid input", () => {
  it.each([
    ["plain text", "just some words", "Not a base16 scheme, VS Code theme, or copied theme."],
    ["broken JSON", '{"colors": {', "This looks like JSON but could not be read."],
    [
      "a VS Code theme without an editor background",
      '{"name": "X", "colors": {"focusBorder": "#123456"}}',
      "This VS Code theme has no editor.background colour.",
    ],
    [
      "a base16 scheme missing a slot",
      NORD.replace(/^\s+base0F:.*\n/m, ""),
      "This base16 scheme is missing base0F.",
    ],
    [
      "a base16 scheme with a bad colour",
      NORD.replace('"#81A1C1"', '"blue"'),
      "base0D is not a hex colour.",
    ],
    [
      "a damaged copied theme",
      "wystack-theme-v1:not-base64!!",
      "This copied theme is incomplete or damaged.",
    ],
  ])("reports %s in one line", (_label, text, error) => {
    expect(importTheme(text)).toEqual({ ok: false, error });
  });
});

describe("exportPreset", () => {
  it.each(THEME_PRESETS.map((p) => [p.name, p] as const))("round-trips %s", (_name, preset) => {
    const back = imported(exportPreset(preset));
    expect(back.name).toBe(preset.name);
    expect(back.overrides).toEqual(preset.overrides);
    expect(back.adjustments).toBeUndefined();
  });

  it("round-trips an imported preset with its adjustments recomputed", () => {
    const nord = imported(NORD);
    const back = imported(exportPreset(nord));
    expect(back.overrides).toEqual(nord.overrides);
  });

  it("clamps a hand-edited copied theme back inside the bounds", () => {
    const loud: ThemePreset = {
      id: "x",
      name: "Loud",
      overrides: {
        light: {
          neutralHue: 30,
          neutralChroma: 0.2,
          surfaceBase: "oklch(0.7 0.3 30)",
          palette: { primary: "oklch(0.9 0.1 30)" },
        },
      },
    };
    const back = imported(exportPreset(loud));
    expect(back.adjustments).toEqual(["contrast", "softened"]);
    expectWithinBounds(back);
    expectAccentPassesAA(back);
  });
});

describe("imported preset ids", () => {
  it("keeps names that slug alike apart", () => {
    const light = { neutralHue: 0 };
    const a = imported(exportPreset({ id: "x", name: "A+B", overrides: { light, dark: {} } }));
    const b = imported(exportPreset({ id: "x", name: "A B", overrides: { light, dark: {} } }));
    expect(a.id).not.toBe(b.id);
  });
});

describe("status colours", () => {
  it("records softening when a status colour loses chroma", () => {
    const loudDanger: ThemePreset = {
      id: "x",
      name: "Loud danger",
      overrides: { light: { palette: { danger: "oklch(0.577 0.3 27)" } }, dark: {} },
    };
    const back = imported(exportPreset(loudDanger));
    expect(back.adjustments).toEqual(["softened"]);
    expect(parseOklch(back.overrides.light!.palette!.danger!).c).toBeLessThan(0.3);
  });
});

describe("built-in presets", () => {
  it.each(THEME_PRESETS.map((p) => [p.name, p] as const))(
    "%s passes AA and stays in bounds",
    (_name, preset) => {
      expectAccentPassesAA(preset);
      expectWithinBounds(preset);
    },
  );
});

describe("readImportedPresets", () => {
  it("restores stored presets and drops malformed entries", () => {
    const nord = imported(NORD);
    const restored = readImportedPresets(JSON.parse(JSON.stringify([nord, { name: 3 }, "junk"])));
    expect(restored).toEqual([nord]);
  });
});
